# Site settings
title: Blog of Tao Huang
description: xxx
baseurl: ""
url: "https://github.com/huangtao36"

# GitHub User settings
username: Tao Huang
github_username: huangtao36
user_description: xxx
user_title: xxx
email: htao36@163.com

# Blog Author settings
author:
  name:           Tao Huang
  picture:
  email:          htao36@163.com
  description:    XXX.
  twitter:
  facebook:
  github:         https://github.com/huangtao36
  linkedin:


# markdown
markdown: kramdown

kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 span:
  line_numbers: false
 block:
  line_numbers: true
  start_line: 1

highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap


permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      numbering: true
      commentable: true
      status: Completed
      protected: false
      rss: true


exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"
 - "*.draft"
