encoding: UTF-8

permalink: /:year/:month/:day/:title.html
paginate: 5
markdown: kramdown

kramdown:
  input: GFM

highlighter: rouge


# 作者信息
author: 
  name: Huang Tao
  email: htao36@163.com
  link: https://huangtao36.github.io/
  weibo: xx
  github: https://github.com/huangtao36
  github_username:  huangtao36
  weibo_username:  xxx

# 站点信息
title : HuangTao's Home
description: 
  xxx
url: https://huangtao36.github.io/
rss_url: /feed.xml

# gavatar头像及Favicon
gavatar : /assets/img/logo.jpg
favicon : /assets/img/logo.png

# disqus 设置
#disqus:
#  shortname: blademastercoder

#profile 个人信息

profile_desc : xxx <br /> xxx<br> #QQ交流群：701451028<br>

# 首页除了最新文章外显示分类
cates: 
- Essay

# 中文本地化
locals: 
   newest : 最新文章